### ISSUE TITLE
Handle redirected items

### ISSUE THREAD

**Issue by connorshea** [connorshea/wikidatum#10]
e.g. Q116169761 is a redirected item, and right now the gem just fails.

```
irb(main):015:0> wikidatum_client.item(id: 'Q116169761')
Something went wrong with this request!
Status Code: 308
""
/Users/connorshea/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/json-2.6.3/lib/json/common.rb:216:in `parse': unexpected token at '' (JSON::ParserError)
	from /Users/connorshea/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/json-2.6.3/lib/json/common.rb:216:in `parse'
	from /Users/connorshea/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/wikidatum-0.3.3/lib/wikidatum/client.rb:416:in `get_request'
	from /Users/connorshea/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/wikidatum-0.3.3/lib/wikidatum/client.rb:108:in `item'
	from (irb):15:in `<main>'
	from /Users/connorshea/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/irb-1.7.4/exe/irb:9:in `<top (required)>'
	from /Users/connorshea/.rbenv/versions/3.1.0/bin/irb:25:in `load'
	from /Users/connorshea/.rbenv/versions/3.1.0/bin/irb:25:in `<main>'
```

**Comment by connorshea** [comment]
I've handled this now :)
